export const ROUTES = {
  LOGIN: "/login",
  OVERVIEW: "/overview",
  CHAT: "/chat",
  CHAT_SESSION: "/chat/:sessionKey",
  AGENTS: "/agents",
  AGENT_DETAIL: "/agents/:id",
  SESSIONS: "/sessions",
  SESSION_DETAIL: "/sessions/:key",
  SKILLS: "/skills",
  SKILL_DETAIL: "/skills/:id",
  CRON: "/cron",
  CRON_DETAIL: "/cron/:id",
  CONFIG: "/config",
  TRACES: "/traces",
  TRACE_DETAIL: "/traces/:id",
  EVENTS: "/events",
  DELEGATIONS: "/delegations",
  USAGE: "/usage",
  CHANNELS: "/channels",
  CHANNEL_DETAIL: "/channels/:id",
  APPROVALS: "/approvals",
  NODES: "/nodes",
  LOGS: "/logs",
  PROVIDERS: "/providers",
  TEAMS: "/teams",
  TEAM_DETAIL: "/teams/:id",
  PROJECTS: "/projects",
  PROJECT_DETAIL: "/projects/:id",
  PROJECTS_SESSION: "/projects/sessions/:id",
  CUSTOM_TOOLS: "/custom-tools",
  BUILTIN_TOOLS: "/builtin-tools",
  MCP: "/mcp",
  TTS: "/tts",
  NEWS_DIGEST: "/news-digest",
  SOCIAL: "/social",
  SOCIAL_POSTS_NEW: "/social/posts/new",
  SOCIAL_POSTS_DETAIL: "/social/posts/:id",
  SOCIAL_POSTS_EDIT: "/social/posts/:id/edit",
  STORAGE: "/storage",
  PENDING_MESSAGES: "/pending-messages",
  MEMORY: "/memory",
  KNOWLEDGE_BASE: "/knowledge-base",
  SETUP: "/setup",
} as const;

export const LOCAL_STORAGE_KEYS = {
  TOKEN: "goclaw:token",
  USER_ID: "goclaw:userId",
  SENDER_ID: "goclaw:senderID",
  THEME: "goclaw:theme",
  SIDEBAR_COLLAPSED: "goclaw:sidebarCollapsed",
} as const;
